before_commands:
    - "composer install --dev --prefer-source"

build_failure_conditions:
    # No new code elements with rating of D or lower
    - 'elements.rating(<= D).new.exists'

    # No new issues with severity MAJOR or higher
    - 'issues.severity(>= MAJOR).new.exists'

    # Minimum code rating: 7
    - 'project.metric("scrutinizer.quality", < 7)'

    # Minimum code coverage: 70%
    - 'project.metric("scrutinizer.test_coverage", < 0.70)'

    # Code coverage must not decrease by more than 5%
    - 'project.metric_change("scrutinizer.test_coverage", < -0.05)'

tools:
    php_code_coverage:
        enabled: true
        test_command: ./vendor/bin/phpunit -c phpunit.xml.dist
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["src/*", "tests/Zf2DoctrineElasticsearchSyncTest/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["tests", "vendor"]
    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: ["src/*", "tests/Zf2DoctrineElasticsearchSyncTest/*"]
    php_loc:
        enabled: true
        excluded_dirs: ["tests", "vendor"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["tests", "vendor"]
    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*", "tests/Zf2DoctrineElasticsearchSyncTest/*"]
    php_hhvm:
        enabled: true
        filter:
            paths: ["src/*", "tests/Zf2DoctrineElasticsearchSyncTest/*"]
    sensiolabs_security_checker: true
